---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-demo
  labels:
    app: hello-demo
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hello-demo
  template:
    metadata:
      labels:
        app: hello-demo
    spec:
      containers:
        - name: hello-demo
          image: "martijnvantiel/helloworld:latest"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
  strategy:
     canary: 
       steps:
       - setWeight: 20
       - pause: {}